---
title: "Course Schedule"
---
The general schedule for the course is below. 
For code, please see [this dropbox](https://www.dropbox.com/sh/objbunt4wxdlnxb/AAB38yRdxi62BlMC1ca_SYPJa?dl=0) for a static view. During the course itself, we'll give you share access so that you can update files as things change. Please [run this script](./files/scripts/Install_Required_Packages.R) in R to install the packages you will need for the course before day 1.  
\
For the course, we'll also use a number of common data sets which you can download (and put into a data folder) [here](files/data.zip).   
\
Lecture recordings are available on [this unlisted youtube playlist](https://youtube.com/playlist?list=PL8ARh53RvgKGxjtPfFxIfr9MfjWW4zjXl).
\
\

## Day 1. Introduction to SEM  
__Overview:__  We discuss just what is SEM. Along the way we'll discuss it's origins, give a general example of moving from a traditional ANOVA-esque framework and to observational data, and finally discuss how to build a well-justified causal model. Causality will be central, and we won't pull any punches! We'll end the day by starting to talk about how to fit SEMs using likelihood using covariance-based estimation with likelihood.  
__Lectures:__  [What is SEM? A Practical and Historical Overview](lecture_pdfs/A_Brief_History.pdf)  
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
	[Anatomy of SEM](lecture_pdfs/The_Basics.pdf)  
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
	[Building Multivariate Causal Models](lecture_pdfs/Multivariate_Causal_Models.pdf), [code](files/scripts/multivariate_causal_models.R)  
	[Jon causality - alternate explanation](lecture_pdfs/Causality (Jon).pdf)  
__Readings:__  [Grace 2010](https://www.dropbox.com/s/zbj2h646z00daxx/Grace%20et%20al%202010%20Ecol%20Monogr.pdf?dl=0) (overview), [Whalen et al. 2013](https://www.dropbox.com/s/cuwk8vngmqjgfgc/Whalen%20et%20al%202013%20Ecology.pdf?dl=0) (example) (note: semclass/semclass for pdfs)  
__Optional Reading:__ [Matsueda 2012](https://www.dropbox.com/s/a2y7z4pmfda1qwq/Matsueda%202012%20history.pdf?dl=0) (history), [Pearl 2012a](https://www.dropbox.com/preview/2020%20Virtual/readings/pearl-causal-lecture.pdf?role=work) (history of causality), [Grace and Irvine 2019](readings/Grace_and_Irvine_2019.pdf) (building causal models for SEM)  
__Etherpad:__ http://etherpad.wikimedia.org/p/sem-eeb-intro-2021  
__Jamboards:__ [Jamboard](https://jamboard.google.com/d/11i20omJK685UKXgNKjewiBJ9bcuYuBW3fQAwqaCKwOE/edit?usp=sharing) and [Jamboard #2](https://jamboard.google.com/d/1HaPb_HXL529uPbDfS78tokR_YdWK7tcJfaF28h5zgxc/edit?usp=sharing)
\
\

## Day 2. Covariance Based SEM  
__Overview:__  We'll discuss covariance-based estimation, how we evaluate an SEM and what we report. We'll end the day (if we have time) exploring the concept of latent variables - variables for which we do not actually have a measured variable, but for which we have one or more indicators.  
__Lectures:__  	[Engines of SEM: Covariance-Based Estimation](lecture_pdfs/Intro_to_Likelihood_Fitting.pdf), [code](files/scripts/Likelihood_Fitting.R)    
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [What does it mean to evaluate a multivariate hypothesis?](lecture_pdfs/Assesing_Likelihood_Fits.pdf), [code](files/scripts/Assessing_Likelihood.R), [fitted_lavaan.R](files/scripts/fitted_lavaan.R)  
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [Latent Variable models](lecture_pdfs/Latent_Variables.pdf), [code](files/scripts/Latent_variables.R)  
__Readings:__  [Grace and Bollen 2005](https://www.dropbox.com/s/s625kis90k33hxn/Grace%20%26%20Bollen%202005%20Bull%20Ecol%20Soc%20Amer.pdf?dl=0)  
__Book Chapter:__ https://jslefche.github.io/sem_book/global-estimation.html  
__Etherpad:__ http://etherpad.wikimedia.org/p/sem-eeb-covariance-2021  

\
\

## Day 3. Piecewise SEM  
__Overview:__  We move beyond covariance based techniques into local estimation techniques that unite the graph theoretic approach with SEM via the `piecewiseSEM` package by Jon Lefcheck.  
__Lectures:__  	[Engines of SEM: Local Estimation with piecewiseSEM](lecture_pdfs/Local_Estimation.pdf), [code](files/scripts/Local_Estimation.R)      
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [A Nonlinear, Non-normal world](lecture_pdfs/Nonlinear_nonnormal.pdf), [code](files/scripts/nonlinear_nonnormal.R)      
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [Categorical Variables and Multigroup Analysis](lecture_pdfs/Categorical_Variables.pdf), [code](files/scripts/Categorical_Vars.R), [multigroup_margins.R](files/scripts/multigroup_margins.R)  
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [Mixed Models in SEM](lecture_pdfs/Mixed_Models.pdf), [code](files/scripts/Mixed_Models.R)    
__Readings:__  [piecewiseSEM vignette](http://jslefche.github.io/piecewiseSEM/articles/piecewiseSEM.html), [Shipley 2009](https://www.dropbox.com/s/junnkl0uvm7h7i7/Shipley%202009%20Ecology.pdf?dl=0), [Lefcheck 2016](https://www.dropbox.com/s/b3usjrtb0d71qzo/Lefcheck%202016%20Methods%20Ecol%20Evol.pdf?dl=0)  
__Book Chapter:__ https://jslefche.github.io/sem_book/local-estimation.html  
__Etherpad:__ http://etherpad.wikimedia.org/p/sem-eeb-piecewise-2021  

\
\

## Day 4. Special Topics in SEM  
__Overview:__  This day varies quite a bit, depending on the current class. It's a potpurri of more advances topics, not all of which will be covered. The good news: you get to choose! Fill out our poll [here](https://forms.gle/QrkC2H2ocNDERC3t7) to indicate your preference by Day 3.  
__Lectures:__  [Engines of SEM: Bayesian SEM](lecture_pdfs/bayesian_sem.pdf), [code](files/scripts/bayesian_sem.R)  
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [Spatial Data in SEM](lecture_pdfs/Spatial_Autocorrelation.pdf), [code](files/scripts/Spatial_autocorrelation.R), [helper functions](files/scripts/residuals.R)   
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [Timseries and Temporal Autocorrelation in SEM](lecture_pdfs/Temporal_Autocorrelation.pdf), [code](files/scripts/Temporal_Autocorrelation.R)   
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [Composite Variables ](lecture_pdfs/Composite_Variables.pdf), [code](files/scripts/Composites.R)   
	&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Whole-System Prediction with SEM  
__Readings:__   [brms and SEM](https://rpubs.com/jebyrnes/brms_bayes_sem). [causal model structure and random effects](https://rpubs.com/jebyrnes/causal_mods)  
__Etherpad:__ http://etherpad.wikimedia.org/p/sem-eeb-advanced-2021  

\
\

## Day 5. Open Lab and Presentations  
__Overview:__  In the morning, we'll have an open lab. Students will work on their own data and projects with an aim to building a 2-3 slide powerpoint presentation detailing 1. The problem/system, 2. The model they built, and 3. The Final result and any challenges. We'll present these in the afternoon, hopefully in a convivial atmosphere, after a brief primer on warming up for a talk you are nervous about!  
__Lectures:__  How to fool yourself with SEM!  
__Etherpad:__ http://etherpad.wikimedia.org/p/sem-eeb-lab-2021  

\
\

